# Site settings
title: Hansenclever Bassani
email: hfb@cin.ufpe.br
description: > # this means to ignore newlines until "baseurl:"
  **Professor** at CIn/UFPE (cin.ufpe.br/~hfb) and Visiting Researcher at Mila/UdeM 
  


baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hfbassani.github.io" # the base hostname & protocol for your site
github_username:  hfbassani

# Build settings
markdown: kramdown

theme: jekyll-theme-modernist