# Site settings
name: Hansenclever Bassani
email: hfb@cin.ufpe.br
title: Ph.D. in Computer Science
description: > # this means to ignore newlines until "baseurl:"
  Professor at <a target='_blank' href='https://cin.ufpe.br'> Universidade Federal de Pernambuco </a>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hfbassani.github.io" # the base hostname & protocol for your site
github_username:  hfbassani

# Build settings
markdown: kramdown
